import { DevelopmentCard, Noble } from "./types"

export const DEVELOPMENT_CARDS: {
    tier1: DevelopmentCard[]
    tier2: DevelopmentCard[]
    tier3: DevelopmentCard[]
} = {
    tier1: [
        { id: 1, cost: { white: 0, blue: 1, green: 1, red: 1, black: 1 }, provides: "white", points: 0 },
        { id: 2, cost: { white: 0, blue: 1, green: 2, red: 1, black: 1 }, provides: "white", points: 0 },
        { id: 3, cost: { white: 0, blue: 2, green: 2, red: 0, black: 1 }, provides: "white", points: 0 },
        { id: 4, cost: { white: 0, blue: 0, green: 3, red: 1, black: 1 }, provides: "white", points: 0 },
        { id: 5, cost: { white: 1, blue: 0, green: 1, red: 1, black: 1 }, provides: "blue", points: 0 },
        { id: 6, cost: { white: 1, blue: 0, green: 1, red: 2, black: 1 }, provides: "blue", points: 0 },
        { id: 7, cost: { white: 1, blue: 0, green: 2, red: 2, black: 0 }, provides: "blue", points: 0 },
        { id: 8, cost: { white: 1, blue: 0, green: 0, red: 1, black: 3 }, provides: "blue", points: 0 },
        { id: 9, cost: { white: 1, blue: 1, green: 0, red: 1, black: 1 }, provides: "green", points: 0 },
        { id: 10, cost: { white: 1, blue: 1, green: 0, red: 1, black: 2 }, provides: "green", points: 0 },
        { id: 11, cost: { white: 0, blue: 2, green: 0, red: 2, black: 1 }, provides: "green", points: 0 },
        { id: 12, cost: { white: 3, blue: 1, green: 0, red: 0, black: 1 }, provides: "green", points: 0 },
        { id: 13, cost: { white: 1, blue: 1, green: 1, red: 0, black: 1 }, provides: "red", points: 0 },
        { id: 14, cost: { white: 2, blue: 1, green: 1, red: 0, black: 1 }, provides: "red", points: 0 },
        { id: 15, cost: { white: 2, blue: 0, green: 1, red: 0, black: 2 }, provides: "red", points: 0 },
        { id: 16, cost: { white: 1, blue: 3, green: 1, red: 0, black: 0 }, provides: "red", points: 0 },
        { id: 17, cost: { white: 1, blue: 1, green: 1, red: 1, black: 0 }, provides: "black", points: 0 },
        { id: 18, cost: { white: 1, blue: 2, green: 1, red: 1, black: 0 }, provides: "black", points: 0 },
        { id: 19, cost: { white: 2, blue: 2, green: 0, red: 1, black: 0 }, provides: "black", points: 0 },
        { id: 20, cost: { white: 0, blue: 0, green: 1, red: 3, black: 1 }, provides: "black", points: 0 },
        { id: 21, cost: { white: 0, blue: 0, green: 0, red: 2, black: 1 }, provides: "white", points: 0 },
        { id: 22, cost: { white: 0, blue: 0, green: 1, red: 1, black: 1 }, provides: "white", points: 0 },
        { id: 23, cost: { white: 0, blue: 0, green: 2, red: 0, black: 2 }, provides: "white", points: 0 },
        { id: 24, cost: { white: 1, blue: 0, green: 0, red: 0, black: 2 }, provides: "white", points: 1 },
        { id: 25, cost: { white: 0, blue: 3, green: 0, red: 0, black: 0 }, provides: "white", points: 1 },
        { id: 26, cost: { white: 1, blue: 0, green: 0, red: 1, black: 2 }, provides: "white", points: 0 },
        { id: 27, cost: { white: 0, blue: 1, green: 0, red: 0, black: 2 }, provides: "white", points: 0 },
        { id: 28, cost: { white: 2, blue: 0, green: 0, red: 2, black: 0 }, provides: "white", points: 0 },
        { id: 29, cost: { white: 1, blue: 0, green: 0, red: 2, black: 0 }, provides: "blue", points: 0 },
        { id: 30, cost: { white: 0, blue: 0, green: 0, red: 1, black: 1 }, provides: "blue", points: 0 },
        { id: 31, cost: { white: 2, blue: 0, green: 0, red: 0, black: 2 }, provides: "blue", points: 0 },
        { id: 32, cost: { white: 0, blue: 1, green: 0, red: 0, black: 2 }, provides: "blue", points: 1 },
        { id: 33, cost: { white: 0, blue: 0, green: 3, red: 0, black: 0 }, provides: "blue", points: 1 },
        { id: 34, cost: { white: 2, blue: 1, green: 0, red: 0, black: 1 }, provides: "blue", points: 0 },
        { id: 35, cost: { white: 2, blue: 0, green: 1, red: 0, black: 0 }, provides: "blue", points: 0 },
        { id: 36, cost: { white: 0, blue: 2, green: 0, red: 0, black: 2 }, provides: "blue", points: 0 },
        { id: 37, cost: { white: 0, blue: 2, green: 0, red: 1, black: 0 }, provides: "green", points: 0 },
        { id: 38, cost: { white: 1, blue: 0, green: 0, red: 0, black: 1 }, provides: "green", points: 0 },
        { id: 39, cost: { white: 0, blue: 2, green: 0, red: 2, black: 0 }, provides: "green", points: 0 },
        { id: 40, cost: { white: 0, blue: 0, green: 1, red: 2, black: 0 }, provides: "green", points: 1 },
        { id: 41, cost: { white: 0, blue: 0, green: 0, red: 3, black: 0 }, provides: "green", points: 1 },
        { id: 42, cost: { white: 1, blue: 1, green: 2, red: 0, black: 0 }, provides: "green", points: 0 },
        { id: 43, cost: { white: 0, blue: 0, green: 2, red: 2, black: 0 }, provides: "green", points: 0 },
        { id: 44, cost: { white: 2, blue: 2, green: 0, red: 0, black: 0 }, provides: "green", points: 0 },
        { id: 45, cost: { white: 2, blue: 0, green: 1, red: 0, black: 0 }, provides: "red", points: 0 },
        { id: 46, cost: { white: 0, blue: 1, green: 0, red: 0, black: 1 }, provides: "red", points: 0 },
        { id: 47, cost: { white: 2, blue: 0, green: 0, red: 0, black: 2 }, provides: "red", points: 0 },
        { id: 48, cost: { white: 2, blue: 0, green: 0, red: 1, black: 0 }, provides: "red", points: 1 },
        { id: 49, cost: { white: 0, blue: 0, green: 0, red: 0, black: 3 }, provides: "red", points: 1 },
        { id: 50, cost: { white: 0, blue: 1, green: 1, red: 2, black: 0 }, provides: "red", points: 0 },
        { id: 51, cost: { white: 0, blue: 0, green: 2, red: 0, black: 2 }, provides: "red", points: 0 },
        { id: 52, cost: { white: 0, blue: 2, green: 2, red: 0, black: 0 }, provides: "red", points: 0 },
        { id: 53, cost: { white: 0, blue: 1, green: 2, red: 0, black: 0 }, provides: "black", points: 0 },
        { id: 54, cost: { white: 1, blue: 0, green: 0, red: 1, black: 0 }, provides: "black", points: 0 },
        { id: 55, cost: { white: 0, blue: 0, green: 2, red: 0, black: 2 }, provides: "black", points: 0 },
        { id: 56, cost: { white: 0, blue: 2, green: 0, red: 0, black: 1 }, provides: "black", points: 1 },
        { id: 57, cost: { white: 3, blue: 0, green: 0, red: 0, black: 0 }, provides: "black", points: 1 },
        { id: 58, cost: { white: 0, blue: 0, green: 1, red: 1, black: 2 }, provides: "black", points: 0 },
        { id: 59, cost: { white: 2, blue: 0, green: 2, red: 0, black: 0 }, provides: "black", points: 0 },
        { id: 60, cost: { white: 2, blue: 2, green: 0, red: 0, black: 0 }, provides: "black", points: 0 },
    ],
    tier2: [
        { id: 61, cost: { white: 3, blue: 2, green: 2, red: 0, black: 0 }, provides: "white", points: 1 },
        { id: 62, cost: { white: 0, blue: 1, green: 4, red: 2, black: 0 }, provides: "white", points: 2 },
        { id: 63, cost: { white: 1, blue: 4, green: 2, red: 0, black: 0 }, provides: "white", points: 2 },
        { id: 64, cost: { white: 0, blue: 0, green: 5, red: 3, black: 0 }, provides: "white", points: 2 },
        { id: 65, cost: { white: 5, blue: 3, green: 0, red: 0, black: 0 }, provides: "white", points: 2 },
        { id: 66, cost: { white: 0, blue: 2, green: 2, red: 3, black: 0 }, provides: "blue", points: 1 },
        { id: 67, cost: { white: 0, blue: 2, green: 1, red: 4, black: 0 }, provides: "blue", points: 2 },
        { id: 68, cost: { white: 0, blue: 0, green: 1, red: 4, black: 2 }, provides: "blue", points: 2 },
        { id: 69, cost: { white: 0, blue: 0, green: 3, red: 5, black: 0 }, provides: "blue", points: 2 },
        { id: 70, cost: { white: 3, blue: 0, green: 0, red: 0, black: 5 }, provides: "blue", points: 2 },
        { id: 71, cost: { white: 0, blue: 3, green: 0, red: 2, black: 2 }, provides: "green", points: 1 },
        { id: 72, cost: { white: 4, blue: 2, green: 0, red: 0, black: 1 }, provides: "green", points: 2 },
        { id: 73, cost: { white: 4, blue: 2, green: 0, red: 1, black: 0 }, provides: "green", points: 2 },
        { id: 74, cost: { white: 5, blue: 3, green: 0, red: 0, black: 0 }, provides: "green", points: 2 },
        { id: 75, cost: { white: 0, blue: 5, green: 0, red: 0, black: 3 }, provides: "green", points: 2 },
        { id: 76, cost: { white: 2, blue: 0, green: 0, red: 2, black: 3 }, provides: "red", points: 1 },
        { id: 77, cost: { white: 1, blue: 0, green: 0, red: 2, black: 4 }, provides: "red", points: 2 },
        { id: 78, cost: { white: 2, blue: 0, green: 1, red: 0, black: 4 }, provides: "red", points: 2 },
        { id: 79, cost: { white: 3, blue: 0, green: 0, red: 0, black: 5 }, provides: "red", points: 2 },
        { id: 80, cost: { white: 0, blue: 0, green: 0, red: 5, black: 3 }, provides: "red", points: 2 },
        { id: 81, cost: { white: 0, blue: 0, green: 3, red: 2, black: 2 }, provides: "black", points: 1 },
        { id: 82, cost: { white: 0, blue: 1, green: 2, red: 0, black: 4 }, provides: "black", points: 2 },
        { id: 83, cost: { white: 2, blue: 0, green: 0, red: 1, black: 4 }, provides: "black", points: 2 },
        { id: 84, cost: { white: 5, blue: 0, green: 0, red: 0, black: 3 }, provides: "black", points: 2 },
        { id: 85, cost: { white: 0, blue: 0, green: 0, red: 3, black: 5 }, provides: "black", points: 2 },
        { id: 86, cost: { white: 0, blue: 5, green: 3, red: 0, black: 0 }, provides: "white", points: 2 },
        { id: 87, cost: { white: 6, blue: 0, green: 0, red: 0, black: 0 }, provides: "white", points: 3 },
        { id: 88, cost: { white: 0, blue: 0, green: 0, red: 6, black: 0 }, provides: "blue", points: 3 },
        { id: 89, cost: { white: 0, blue: 0, green: 6, red: 0, black: 0 }, provides: "green", points: 3 },
        { id: 90, cost: { white: 0, blue: 0, green: 0, red: 0, black: 6 }, provides: "red", points: 3 },
    ],
    tier3: [
        { id: 91, cost: { white: 3, blue: 3, green: 5, red: 3, black: 0 }, provides: "white", points: 3 },
        { id: 92, cost: { white: 7, blue: 0, green: 0, red: 0, black: 0 }, provides: "white", points: 4 },
        { id: 93, cost: { white: 6, blue: 3, green: 0, red: 0, black: 3 }, provides: "white", points: 4 },
        { id: 94, cost: { white: 7, blue: 3, green: 0, red: 0, black: 0 }, provides: "white", points: 5 },
        { id: 95, cost: { white: 0, blue: 3, green: 3, red: 5, black: 3 }, provides: "blue", points: 3 },
        { id: 96, cost: { white: 0, blue: 7, green: 0, red: 0, black: 0 }, provides: "blue", points: 4 },
        { id: 97, cost: { white: 3, blue: 6, green: 0, red: 0, black: 3 }, provides: "blue", points: 4 },
        { id: 98, cost: { white: 0, blue: 7, green: 3, red: 0, black: 0 }, provides: "blue", points: 5 },
        { id: 99, cost: { white: 3, blue: 0, green: 3, red: 3, black: 5 }, provides: "green", points: 3 },
        { id: 100, cost: { white: 0, blue: 0, green: 7, red: 0, black: 0 }, provides: "green", points: 4 },
        { id: 101, cost: { white: 3, blue: 0, green: 6, red: 3, black: 0 }, provides: "green", points: 4 },
        { id: 102, cost: { white: 0, blue: 0, green: 7, red: 3, black: 0 }, provides: "green", points: 5 },
        { id: 103, cost: { white: 5, blue: 3, green: 0, red: 3, black: 3 }, provides: "red", points: 3 },
        { id: 104, cost: { white: 0, blue: 0, green: 0, red: 7, black: 0 }, provides: "red", points: 4 },
        { id: 105, cost: { white: 0, blue: 3, green: 0, red: 6, black: 3 }, provides: "red", points: 4 },
        { id: 106, cost: { white: 0, blue: 0, green: 0, red: 7, black: 3 }, provides: "red", points: 5 },
        { id: 107, cost: { white: 3, blue: 5, green: 3, red: 0, black: 3 }, provides: "black", points: 3 },
        { id: 108, cost: { white: 0, blue: 0, green: 0, red: 0, black: 7 }, provides: "black", points: 4 },
        { id: 109, cost: { white: 0, blue: 0, green: 3, red: 3, black: 6 }, provides: "black", points: 4 },
        { id: 110, cost: { white: 3, blue: 0, green: 0, red: 0, black: 7 }, provides: "black", points: 5 },
    ],
}

export const NOBLES: Noble[] = [
    { id: 1, requirements: { white: 3, blue: 3, green: 3, red: 0, black: 0 }, points: 3 },
    { id: 2, requirements: { white: 0, blue: 3, green: 3, red: 3, black: 0 }, points: 3 },
    { id: 3, requirements: { white: 0, blue: 0, green: 3, red: 3, black: 3 }, points: 3 },
    { id: 4, requirements: { white: 3, blue: 0, green: 0, red: 3, black: 3 }, points: 3 },
    { id: 5, requirements: { white: 3, blue: 3, green: 0, red: 0, black: 3 }, points: 3 },
    { id: 6, requirements: { white: 0, blue: 4, green: 4, red: 0, black: 0 }, points: 3 },
    { id: 7, requirements: { white: 0, blue: 0, green: 4, red: 4, black: 0 }, points: 3 },
    { id: 8, requirements: { white: 0, blue: 0, green: 0, red: 4, black: 4 }, points: 3 },
    { id: 9, requirements: { white: 4, blue: 0, green: 0, red: 0, black: 4 }, points: 3 },
    { id: 10, requirements: { white: 4, blue: 4, green: 0, red: 0, black: 0 }, points: 3 },
]
